spring:
  datasource:
    username: root
    password: 123456a@
#    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://103.161.181.124:3306/iotdevices
    driver-class-name: com.mysql.cj.jdbc.Driver
#    platform: h2
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:smartfarm
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    converters:
      preferred-json-mapper: gson
server:
  port: 5555